gcc-15: Update to 15.2.0
The build system of some Rust package (for example oma) passes "--target
loongarch64-unknown-linux-gnu" to clang++, triggering an error without
this symlink if gcc-15 is installed:

    In file included from <stdin>:1:
    In file included from /usr/lib64/gcc/loongarch64-unknown-linux-gnu/15.1.0/../../../../include/c++/15.1.0/algorithm:62:
    /usr/lib64/gcc/loongarch64-unknown-linux-gnu/15.1.0/../../../../include/c++/15.1.0/bits/stl_algobase.h:59:10: fatal error: 'bits/c++config.h' file not found
       59 | #include <bits/c++config.h>
          |          ^~~~~~~~~~~~~~~~~~
    1 error generated.

Create this symlink (like what we do for gcc) to fix it.

Drop upstreamed patch for ext-dce issue which had broken MIPS.

Add patches for severe performance degration caused by RA issue with
-mtune=la664 and the ICE building highway testsuite.

Tracking AOSC patches at AOSC-Tracking/gcc @ aosc/releases/15.2.0
(HEAD: 425fe9a6644754347147e061bcad159bd4a8a1ca).