lxc: update to 5.0.2
- Drop unmaintained cgmanager dep.
- (loongarch64) disable seccomp support.

FIXME: ../src/lxc/seccomp.c:1132:41: error: passing argument 3 of
‘parse_config_v2’ from incompatible pointer type
[-Werror=incompatible-pointer-types]