serf: (Gentoo patches) fix compatibility with OpenSSL 3
`svn` returns undefined reference to `ERR_GET_FUNC'. This was caused by symbol
incompatibility with OpenSSL 3.

Ref: https://bugs.gentoo.org/805161