git-branchles: (fix FTBFS) update to 0.11.1
See [1]. Also see [2].

* Also enforce FAIL_ARCH expression in Bash's extglob form.
* Also disable build for loongarch64_nosimd.

[1]:
error[E0308]: `match` arms have incompatible types
   --> /root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/esl01-indexedlog-0.3.0/src/lock.rs:138:30
    |
134 | /         match (opts.exclusive, opts.non_blocking) {
135 | |             (true, false) => file.lock_exclusive(),
    | |                              --------------------- this is found to be of type `std::result::Result<(), std::io::Error>`
136 | |             (true, true) => file.try_lock_exclusive(),
    | |                             ------------------------- this is found to be of type `std::result::Result<(), std::io::Error>`
137 | |             (false, false) => file.lock_shared(),
    | |                               ------------------ this is found to be of type `std::result::Result<(), std::io::Error>`
138 | |             (false, true) => file.try_lock_shared(),
    | |                              ^^^^^^^^^^^^^^^^^^^^^^ expected `Result<(), Error>`, found `Result<(), TryLockError>`
139 | |         }
    | |_________- `match` arms have incompatible types
    |
    = note: expected enum `std::result::Result<_, std::io::Error>`
               found enum `std::result::Result<_, std::fs::TryLockError>`

For more information about this error, try `rustc --explain E0308`.
   Compiling git-version v0.3.9
error: could not compile `esl01-indexedlog` (lib) due to 1 previous error

[2]: https://github.com/arxanas/git-branchless/issues/1585