ldc: attempt to fix build on ppc32be (FTBFS)
[ 57%] Generating bin/ldc2
/var/cache/acbs/build/acbs.oilp725k/ldc-1.10.0-src/ld: bss-plt forced due to /var/cache/acbs/build/acbs.oilp725k/ldc-1.10.0-src/build/bin/ldc2.o
/var/cache/acbs/build/acbs.oilp725k/ldc-1.10.0-src/build/lib/libldc.a(logger.cpp.o): In function `Logger::attention(Loc&, char const*, ...)':
logger.cpp:(.text._ZN6Logger9attentionER3LocPKcz+0x8c): undefined reference to `vwarning(Loc const&, char const*, __va_list_tag*)'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/ldc2.dir/build.make:62: bin/ldc2] Error 1
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/ldc2.dir/all] Error 2
make: *** [Makefile:163: all] Error 2