linux-kernel: mipsel: fix "utf8_pos symbol undefined"
Compiling CONFIG_FRAMEBUFFER_CONSOLE as module causes:

  ERROR: "utf8_pos" [drivers/video/console/fbcon_ud.ko] undefined!
  ERROR: "utf8_pos" [drivers/video/console/fbcon_cw.ko] undefined!
  ERROR: "utf8_pos" [drivers/video/console/fbcon_ccw.ko] undefined!
  ERROR: "fbcon_is_softback" [drivers/video/console/bitblit.ko] undefined!

This might be a mistake, since on other platforms this is 'y'.