virglrenderer: update to 0.10.4
- Specify options explicitly where applicable.
- Use Git source.

Note: -Dplatforms: Platforms support, set to auto to enable all.
Note: Venus and render server are still experimental.

FIXME: minigbm_allocation breaks build at src/vrend_renderer.c
../src/vrend_renderer.c:7887:19: error: implicit declaration of function
‘gbm_bo_get_plane_size’; did you mean ‘gbm_bo_get_plane_count’?
[-Werror=implicit-function-declaration]
7887 |       gr->size += gbm_bo_get_plane_size(bo, plane);
     |                   ^~~~~~~~~~~~~~~~~~~~~
     |                   gbm_bo_get_plane_count