cbc: fix variable & constant name conflict
Variable name 'mips' in CbcModel.hpp will trigger an error
during compilation:

  CbcModel.hpp:2397:78: error: expected ',' or '...' before numeric constant

on mips* platforms. Somewhere before has defined such constant
so we change the variable name to fix the problem.