libgcrypt: update to 1.11.2, fix FTBFS
The -O flag is not munged correctly during configuration:

In file included from /var/cache/acbs/build/acbs.2bxw905p/libgcrypt-1.11.0/random/rndjent.c:99:
/var/cache/acbs/build/acbs.2bxw905p/libgcrypt-1.11.0/random/jitterentropy-base.c:58:3: error: #error "The CPU Jitter random number generator must not be compiled with optimizations. See documentation. Use the compiler switch -O0 for compiling jitterentropy.c."
   58 |  #error "The CPU Jitter random number generator must not be compiled with optimizations. See documentation. Use the compiler switch -O0 for compiling jitterentropy.c."
      |   ^~~~~