pgadmin: update to 2.0
Currently unusable:

Python path:  "/usr/lib/pgadmin4/venv/lib/python3.6/site-packages:/usr/lib/python3.6/site-packages:/usr/lib/python3.6"
Python Home:  "/usr/lib/pgadmin4/venv"
Traceback (most recent call last):
  File "/usr/lib/python3.6/encodings/__init__.py", line 31, in <module>
    import codecs
  File "/usr/lib/python3.6/codecs.py", line 95
    *, _is_text_encoding=None):
     ^
SyntaxError: invalid syntax