linux-kernel: upgrade to 6.2.10, fix nr_cpus and patch application
- Additional patch to fix undefined reference to `free_io_pgtable_ops'
- Updated config for ppc64el/mips64r6el f.t. Mingcong Bai